version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"  
    volumes:
      - .:/app    
  
  messages:
    build: messages/
    depends_on:
      - app
    

